import React, { useCallback, useMemo, useState } from "react";
import createApolloClient from "../apollo-client";
import Head from "next/head";
import { Flex, ListItem, OrderedList } from "@chakra-ui/react";
import { GET_COUNTRIES } from "../src/graphql/queries/countries";
import { CountryModal } from "../src/components/CountryModal";

export default function Info({ countries }) {
  const [countryModalCode, setCountryModalCode] = useState();

  const country = useMemo(
    () => countries.find(({ code }) => code === countryModalCode),
    [countries, countryModalCode]
  );

  const onClose = useCallback(() => {
    setCountryModalCode();
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Flex
        direction="column"
        p={10}
        color="#000"
        bg="#f2c0f2;"
        rounded="xl"
        shadow="xl"
      >
        <OrderedList>
          {countries.map(({ code, name }) => (
            <ListItem
              key={code}
              cursor="pointer"
              onClick={() => setCountryModalCode(code)}
            >
              {name}
            </ListItem>
          ))}
        </OrderedList>
      </Flex>

      <CountryModal country={country} onClose={onClose} />
    </>
  );
}

export async function getServerSideProps() {
  const client = createApolloClient();
  const { data } = await client.query({
    query: GET_COUNTRIES,
  });

  return {
    props: {
      countries: data.countries.slice(0, 20),
    },
  };
}
